version: 2.1
jobs:
  build:
    docker:
      - image: blurrcat/docker-elm-build
    working_directory: ~/threeBody
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - elm-19-{{ checksum "elm.json" }}
      - run: |
          npm install
      - run: |
          NODE_ENV=production sysconfcpus -n 1 npm run build
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - save_cache:
          key: elm-19-{{ checksum "elm.json" }}
          paths:
            - "./elm-stuff"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cat >> ~/.ssh/config << EOF
              VerifyHostKeyDNS yes
              StrictHostKeyChecking no
            EOF
              git remote add dokku dokku@seattle.blurrcat.net:g
              git config user.name "blurrcat"
              git config user.email "blurrcat@gmail.com"
              ./deploy.sh
            fi
